disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - force_try
  - nesting
  - todo
  - xctfail_message
  - orphaned_doc_comment
  - inclusive_language
  - function_body_length
  - file_length
  - type_body_length
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - file_header
  - multiline_parameters
  - vertical_parameter_alignment_on_call
  - unused_optional_binding
  - fallthrough
  - identifier_name
  - type_name
  - redundant_discardable_let
included:
  - Sources
excluded:
  - Sources/Flow/Protobuf
function_parameter_count:
  warning: 20
  error: 25
line_length:
  warning: 250
  error: 450
large_tuple:
  warning: 4
trailing_comma:
  mandatory_comma: true
identifier_name:
  min_length: 1
  allowed_symbols: ["_"]
type_name:
  min_length: 2
superfluous_disable_command: warning
reporter: "xcode"
